version: "3.7"

volumes:
  tiledesk-datadb:

services:
  # === PROXY de Tiledesk (único puerto público) ===
  proxy:
    image: tiledesk/tiledesk-docker-proxy:v1.1.2
    container_name: tiledesk-docker-proxy
    depends_on:
      - server
      - dashboard
      - webwidget
      - chat21httpserver
      - rabbitmq
      - cds
    ports:
      - "3010:80"          # ← PUERTO PÚBLICO ÚNICO (cámbialo si quieres)
    command: [ "nginx-debug", "-g", "daemon off;" ]
    restart: unless-stopped

  # === Dashboard (panel) ===
  dashboard:
    image: tiledesk/tiledesk-dashboard:2.7.93
    container_name: dashboard
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - BOT_CREDENTIAL_URL=/api/modules/dialogflow/botcredendials/
      - RASA_BOT_CREDENTIAL_URL=/api/modules/rasa/botcredendials/
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - SERVER_BASE_URL=/api/
      - CHAT_BASE_URL=/chat/
      - CDS_BASE_URL=/cds/
      - WS_URL_RELATIVE=/ws/
      - CHAT21_ENGINE=mqtt
      - UPLOAD_ENGINE=native
      - LOG_LEVEL=info
      - APPS_URL=/api/modules/apps/
      - API_BASEIMAGE_URL=/api/
      - COMMUNITY_TEMPLATES_URL=/api/modules/templates/public/community
      - TEMPLATES_URL=/api/modules/templates/public/templates
      - FILE_UPLOAD_ACCEPT=*/*
    expose:
      - "80"
    restart: unless-stopped

  # === Design Studio (CDS) ===
  cds:
    image: tiledesk/design-studio:1.30.4
    container_name: cds
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - SERVER_BASE_URL=/api/
      - DASHBOARD_URL=/dashboard/
      - WS_URL_RELATIVE=/ws/
      - UPLOAD_ENGINE=native
      - LOG_LEVEL=info
      - CDS_STORAGE_PREFIX=cds_sv5
      - API_BASEIMAGE_URL=/api/
      - FILE_UPLOAD_ACCEPT=*/*
      - AI_MODELS=${CDS_AI_MODELS}
    expose:
      - "80"
    restart: unless-stopped

  # === Web Widget ===
  webwidget:
    image: chat21/chat21-web-widget:5.0.93
    container_name: chat21-web-widget
    environment:
      - CHAT21_ENGINE=mqtt
      - MQTT_APPID=tilechat
      - PUSH_ENGINE=none
      - LOG_LEVEL=info
      - MQTT_ENDPOINT=${EXTERNAL_MQTT_BASE_URL}/mqws/ws
      - MQTT_APIENDPOINT=${EXTERNAL_BASE_URL}/chatapi/api
      - SERVER_BASE_URL=${EXTERNAL_BASE_URL}/api/
      - TRANSLATIONS_URL=${EXTERNAL_BASE_URL}/api/
      - API_BASEIMAGE_URL=${EXTERNAL_BASE_URL}/api/
      - DASHBOARD_URL=/dashboard/
      - AUTH_PERSISTENCE=LOCAL
      - ENBED_JS=true
      - FILE_UPLOAD_ACCEPT=*/*
    expose:
      - "80"
    restart: unless-stopped

  # === App móvil demo (opcional). Puedes eliminar este servicio. ===
  ionic:
    image: chat21/chat21-ionic:3.4.13
    container_name: chat21-ionic
    environment:
      - DASHBOARD_URL=/dashboard/
      - API_BASEIMAGE_URL=/api/
      - SERVER_BASE_URL=/api/
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - WIDGET_LOCATION=/widget/
      - PUSH_ENGINE=none
      - LOG_LEVEL=info
      - FILE_UPLOAD_ACCEPT=*/*
      - CHAT21_ENGINE=mqtt
      - MQTT_APPID=tilechat
      - MQTT_ENDPOINT=${EXTERNAL_MQTT_BASE_URL}/mqws/ws
      - MQTT_APIENDPOINT=/chatapi/api
      - SUPPORT_MODE=true
      - WRITE_TO_BUTTON=true
      - ARCHIVED_BUTTON=true
      - AUTH_PERSISTENCE=LOCAL
      - EMAIL_SECTION=true
      - CHAT_STORAGE_PREFIX=chat_sv5
      - WS_URL_RELATIVE=/ws/
    expose:
      - "80"
    restart: unless-stopped

  # === Chatbot (Tilebot) ===
  chatbot:
    image: tiledesk/tiledesk-chatbot:2.0.7
    container_name: chatbot
    environment:
      - API_ENDPOINT=http://server:3000
      - TILEBOT_ENDPOINT=http://chatbot:3000
      - API_URL=${EXTERNAL_BASE_URL}/api
      - MONGODB_URI=mongodb://mongo/tiledesk
      - CACHE_ENABLED=true
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - TILEBOT_LOG=info
      - AI_ENDPOINT=http://ai:8000/api
    depends_on:
      - mongo
    expose:
      - "3000"
    restart: unless-stopped

  # === API (tiledesk-server) ===
  server:
    image: tiledesk/tiledesk-server:2.10.75
    container_name: server
    restart: always
    environment:
      - LOG_LEVEL=info
      - CHAT21_ENABLED=true
      - CHAT21_ENGINE=mqtt
      - CHAT21_URL=http://chat21httpserver:8004
      - CHAT21_JWT_SECRET=tokenKey
      - CHAT21_APPID=tilechat
      - RESTHOOK_ENABLED=true
      - ALLOW_REOPEN_CHAT=true
      - CHAT21_ADMIN_TOKEN=${CHAT21_ADMIN_TOKEN}
      - AMQP_MANAGER_URL=${AMQP_MANAGER_URL}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URI=${MONGODB_URI}                # compat
      - EMAIL_ENABLED=${EMAIL_ENABLED}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_BASEURL=${EXTERNAL_BASE_URL}/dashboard
      - WEBHOOK_ORIGIN=${EXTERNAL_BASE_URL}/api/
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - WS_SERVER_PATH
      - LICENSE_KEY=${LICENSE_KEY}
      - CACHE_ENABLED=true
      - CACHE_ENGINE=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - APPS_ACCESS_TOKEN_SECRET=${APPS_ACCESS_TOKEN_SECRET}
      - BOOT_LOADING=true
      - META_GRAPH_URL=https://graph.facebook.com/v14.0/
      - WHATSAPP_LOG=false
      - TELEGRAM_API_URL=https://api.telegram.org/bot
      - TELEGRAM_FILE_URL=https://api.telegram.org/file/bot
      - TELEGRAM_LOG=info
      - FB_APP_ID=${FB_APP_ID}
      - FB_APP_SECRET=${FB_APP_SECRET}
      - BASE_FILE_URL=${EXTERNAL_BASE_URL}/api/
      - GPTKEY=${GPTKEY}
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - KB_ENDPOINT=${KB_ENDPOINT}
      - QUOTES_ENABLED=false
      - TILEBOT_ENDPOINT=http://chatbot:3000
      - GLOBAL_SECRET=${GLOBAL_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SUPER_PASSWORD=${SUPER_PASSWORD}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - mongo
      - redis
      - rabbitmq
    expose:
      - "3000"

  # === Chat21 HTTP (notificaciones push / webhooks) ===
  chat21httpserver:
    image: chat21/chat21-http-server:0.2.37
    container_name: chat21httpserver
    restart: always
    environment:
      - LOG_LEVEL=info
      - MONGODB_URI=mongodb://mongo/chat21
      - JWT_KEY=tokenKey
      - RABBITMQ_URI=${RABBITMQ_URI}
      - PUSH_ENABLED=true
      - PUSH_WH_NOTIFY_URL=http://localhost:8004/api/tilechat/notify
      - PUSH_WH_WEBHOOK_TOKEN=${PUSH_WH_WEBHOOK_TOKEN}
      - CHAT21HTTP_CACHE_ENABLED=false
      - CONTACTS_LOOKUP_ENDPOINT=http://server:3000/users_util
    depends_on:
      - mongo
      - rabbitmq
    expose:
      - "8004"

  # === Chat21 Realtime (websocket/mqtt bridge) ===
  chat21server:
    image: chat21/chat21-server:0.2.53
    container_name: chat21server
    restart: always
    environment:
      - LOG_LEVEL=info
      - MONGODB_URI=mongodb://mongo/chat21
      - APP_ID=tilechat
      - WEBHOOK_ENDPOINTS=http://server:3000/chat21/requests,http://chat21httpserver:8004/api/tilechat/push/webhook/endpoint/${PUSH_WH_WEBHOOK_TOKEN}
      - WEBHOOK_ENABLED=true
      - WEBHOOK_EVENTS=message-sent,message-delivered,conversation-unarchived
      - RABBITMQ_URI=${RABBITMQ_URI}
    depends_on:
      - mongo
      - rabbitmq
      - server
    expose:
      - "3030"

  # === AI lite (opcional) ===
  ai:
    image: tiledesk/tiledeskai-lite:0.1.0
    container_name: ai
    environment:
      - WORKERS=3
      - TIMEOUT=180
      - MAXREQUESTS=1200
      - MAXRJITTER=5
      - GRACEFULTIMEOUT=30
    expose:
      - "8000"
    restart: unless-stopped

  # === Mensajería ===
  rabbitmq:
    image: chat21/chat21-rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    # Puertos de gestión cerrados al exterior
    expose:
      - "5672"
      - "15672"
      - "1883"
      - "15675"
    restart: unless-stopped

  # === MongoDB ===
  mongo:
    image: mongo:7.0.2
    container_name: mongo
    command: --bind_ip_all
    volumes:
      - tiledesk-datadb:/data/db
    restart: unless-stopped

  # === Redis (cache) ===
  redis:
    image: redis:7.0.5
    container_name: redis
    expose:
      - "6379"
    restart: unless-stopped
