services:
  proxy:
    image: tiledesk/tiledesk-docker-proxy:v1.1.2
    depends_on:
      - server
      - dashboard
      - webwidget
      - chat21httpserver
      - rabbitmq
      - cds
      - ionic
    command: ["nginx-debug", "-g", "daemon off;"]
    expose:
      - "80"
    restart: unless-stopped

  server:
    image: tiledesk/tiledesk-server:2.10.75
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URI=${MONGODB_URI}
      - GLOBAL_SECRET=${GLOBAL_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SUPER_PASSWORD=${SUPER_PASSWORD}
      - EMAIL_ENABLED=${EMAIL_ENABLED}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_BASEURL=${EXTERNAL_BASE_URL}/dashboard
      - WEBHOOK_ORIGIN=${EXTERNAL_BASE_URL}/api/
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - APPS_ACCESS_TOKEN_SECRET=${APPS_ACCESS_TOKEN_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CHAT21_ENABLED=true
      - CHAT21_ENGINE=mqtt
      - CHAT21_URL=http://chat21httpserver:8004
      - CHAT21_JWT_SECRET=tokenKey
      - CHAT21_APPID=tilechat
      - RESTHOOK_ENABLED=true
      - ALLOW_REOPEN_CHAT=true
      - RABBITMQ_URI=${RABBITMQ_URI}
    depends_on:
      - redis
      - rabbitmq
    expose:
      - "3000"
    restart: unless-stopped

  dashboard:
    image: tiledesk/tiledesk-dashboard:2.7.93
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - SERVER_BASE_URL=/api/
      - CHAT_BASE_URL=/chat/
      - CDS_BASE_URL=/cds/
      - WS_URL_RELATIVE=/ws/
    expose:
      - "80"
    restart: unless-stopped

  cds:
    image: tiledesk/design-studio:1.30.4
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - SERVER_BASE_URL=/api/
      - DASHBOARD_URL=/dashboard/
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - WS_URL_RELATIVE=/ws/
      - CDS_STORAGE_PREFIX=cds_sv5
      - AI_MODELS=${CDS_AI_MOD_
