volumes:
  tiledesk-datadb:

services:
  proxy:
    image: tiledesk/tiledesk-docker-proxy:v1.1.2
    depends_on:
      - server
      - dashboard
      - webwidget
      - chat21httpserver
      - rabbitmq
      - cds
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - "8081:80"   # host 8081 -> contenedor 80 (oficial)
    restart: unless-stopped

  server:
    image: tiledesk/tiledesk-server:2.10.75
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URI=${MONGODB_URI}
      - GLOBAL_SECRET=${GLOBAL_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SUPER_PASSWORD=${SUPER_PASSWORD}
      - EMAIL_ENABLED=${EMAIL_ENABLED}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_BASEURL=${EXTERNAL_BASE_URL}/dashboard
      - WEBHOOK_ORIGIN=${EXTERNAL_BASE_URL}/api/
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - APPS_ACCESS_TOKEN_SECRET=${APPS_ACCESS_TOKEN_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - redis
      - rabbitmq
    expose:
      - "3000"
    restart: unless-stopped

  dashboard:
    image: tiledesk/tiledesk-dashboard:2.7.93
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - SERVER_BASE_URL=/api/
      - CHAT_BASE_URL=/chat/
      - CDS_BASE_URL=/cds/
      - WS_URL_RELATIVE=/ws/
    expose:
      - "80"
    restart: unless-stopped

  cds:
    image: tiledesk/design-studio:1.30.4
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - SERVER_BASE_URL=/api/
      - DASHBOARD_URL=/dashboard/
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - WS_URL_RELATIVE=/ws/
      - CDS_STORAGE_PREFIX=cds_sv5
      - AI_MODELS=${CDS_AI_MODELS}
    expose:
      - "80"
    restart: unless-stopped

  webwidget:
    image: chat21/chat21-web-widget:5.0.93
    environment:
      - SERVER_BASE_URL=${EXTERNAL_BASE_URL}/api/
      - DASHBOARD_URL=/dashboard/
      - MQTT_ENDPOINT=${EXTERNAL_BASE_URL}/mqws/ws
      - MQTT_APIENDPOINT=${EXTERNAL_BASE_URL}/chatapi/api
    expose:
      - "80"
    restart: unless-stopped

  chat21httpserver:
    image: chat21/chat21-http-server:0.2.37
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - PUSH_WH_WEBHOOK_TOKEN=${PUSH_WH_WEBHOOK_TOKEN}
    depends_on:
      - rabbitmq
    expose:
      - "8004"
    restart: unless-stopped

  chat21server:
    image: chat21/chat21-server:0.2.53
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - APP_ID=tilechat
      - WEBHOOK_ENDPOINTS=http://server:3000/chat21/requests
    depends_on:
      - rabbitmq
      - server
    expose:
      - "3030"
    restart: unless-stopped

  rabbitmq:
    image: chat21/chat21-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    expose:
      - "5672"
      - "15672"
    restart: unless-stopped

  redis:
    image: redis:7.0.5
    expose:
      - "6379"
    restart: unless-stopped
