services:
  tiledesk-compose:  # proxy usado por EasyPanel como servicio principal
    image: tiledesk/tiledesk-docker-proxy:v1.1.2
    depends_on:
      - server
      - dashboard
      - webwidget
      - chat21httpserver
      - rabbitmq
      - cds
      - ionic
    command: ["nginx-debug", "-g", "daemon off;"]
    expose:
      - "80"    # ← SIN ports; EasyPanel hará 3020 -> 80
    restart: unless-stopped

  server:
    image: tiledesk/tiledesk-server:2.10.75
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URI=${MONGODB_URI}
      - GLOBAL_SECRET=${GLOBAL_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SUPER_PASSWORD=${SUPER_PASSWORD}
      - APPS_ACCESS_TOKEN_SECRET=${APPS_ACCESS_TOKEN_SECRET}
      - EMAIL_ENABLED=${EMAIL_ENABLED}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_BASEURL=${EXTERNAL_BASE_URL}/dashboard
      - WEBHOOK_ORIGIN=${EXTERNAL_BASE_URL}/api/
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - BASE_FILE_URL=${EXTERNAL_BASE_URL}/api/
      - RABBITMQ_URI=${RABBITMQ_URI}
      - CHAT21_JWT_SECRET=${CHAT21_JWT_SECRET}
      - CHAT21_ENABLED=true
      - CHAT21_ENGINE=mqtt
      - CHAT21_URL=http://chat21httpserver:8004
      - CHAT21_APPID=tilechat
      - CHAT21_ADMIN_TOKEN=${CHAT21_ADMIN_TOKEN}
      - CACHE_ENABLED=true
      - CACHE_ENGINE=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CORS_ORIGIN=${CORS_ORIGIN}
      - LICENSE_KEY=${LICENSE_KEY}
      - GPTKEY=${GPTKEY}
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - KB_ENDPOINT=${KB_ENDPOINT}
      - RESTHOOK_ENABLED=true
      - ALLOW_REOPEN_CHAT=true
      - BOOT_LOADING=true
      - LOG_LEVEL=info
    depends_on:
      - redis
      - rabbitmq
    expose:
      - "3000"
    restart: unless-stopped

  dashboard:
    image: tiledesk/tiledesk-dashboard:2.7.93
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - SERVER_BASE_URL=/api/
      - CHAT_BASE_URL=/chat/
      - CDS_BASE_URL=/cds/
      - WS_URL_RELATIVE=/ws/
      - CHAT21_ENGINE=mqtt
      - UPLOAD_ENGINE=native
      - LOG_LEVEL=info
      - APPS_URL=/api/modules/apps/
      - API_BASEIMAGE_URL=/api/
      - COMMUNITY_TEMPLATES_URL=/api/modules/templates/public/community
      - TEMPLATES_URL=/api/modules/templates/public/templates
      - FILE_UPLOAD_ACCEPT=*/*
    expose:
      - "80"
    restart: unless-stopped

  cds:
    image: tiledesk/design-studio:1.30.4
    environment:
      - FEATURES_TOKEN=${FEATURES_TOKEN}
      - WIDGET_LOCATION=${EXTERNAL_BASE_URL}/widget/
      - SERVER_BASE_URL=/api/
      - DASHBOARD_URL=/dashboard/
      - WS_URL_RELATIVE=/ws/
      - UPLOAD_ENGINE=native
      - LOG_LEVEL=info
      - CDS_STORAGE_PREFIX=cds_sv5
      - API_BASEIMAGE_URL=/api/
      - FILE_UPLOAD_ACCEPT=*/*
      - AI_MODELS=${CDS_AI_MODELS}
    expose:
      - "80"
    restart: unless-stopped

  webwidget:
    image: chat21/chat21-web-widget:5.0.93
    environment:
      - CHAT21_ENGINE=mqtt
      - MQTT_APPID=tilechat
      - PUSH_ENGINE=none
      - LOG_LEVEL=info
      - MQTT_ENDPOINT=${EXTERNAL_BASE_URL}/mqws/ws
      - MQTT_APIENDPOINT=${EXTERNAL_BASE_URL}/chatapi/api
      - SERVER_BASE_URL=${EXTERNAL_BASE_URL}/api/
      - TRANSLATIONS_URL=${EXTERNAL_BASE_URL}/api/
      - API_BASEIMAGE_URL=${EXTERNAL_BASE_URL}/api/
      - DASHBOARD_URL=/dashboard/
      - AUTH_PERSISTENCE=LOCAL
      - ENBED_JS=true
      - FILE_UPLOAD_ACCEPT=*/*
    expose:
      - "80"
    restart: unless-stopped

  ionic:
    image: chat21/chat21-ionic:3.4.13
    expose:
      - "80"
    restart: unless-stopped

  chat21httpserver:
    image: chat21/chat21-http-server:0.2.37
    environment:
      - LOG_LEVEL=info
      - MONGODB_URI=${CHAT21_MONGODB_URI}
      - JWT_KEY=${CHAT21_JWT_SECRET}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - PUSH_ENABLED=true
      - PUSH_WH_NOTIFY_URL=http://localhost:8004/api/tilechat/notify
      - PUSH_WH_WEBHOOK_TOKEN=${PUSH_WH_WEBHOOK_TOKEN}
      - CHAT21HTTP_CACHE_ENABLED=false
      - CONTACTS_LOOKUP_ENDPOINT=http://server:3000/users_util
    depends_on:
      - rabbitmq
    expose:
      - "8004"
    restart: unless-stopped

  chat21server:
    image: chat21/chat21-server:0.2.53
    environment:
      - LOG_LEVEL=info
      - MONGODB_URI=${CHAT21_MONGODB_URI}
      - APP_ID=tilechat
      - WEBHOOK_ENDPOINTS=http://server:3000/chat21/requests,http://chat21httpserver:8004/api/tilechat/push/webhook/endpoint/${PUSH_WH_WEBHOOK_TOKEN}
      - WEBHOOK_ENABLED=true
      - WEBHOOK_EVENTS=message-sent,message-delivered,conversation-unarchived
      - RABBITMQ_URI=${RABBITMQ_URI}
    depends_on:
      - chat21httpserver
      - rabbitmq
      - server
    expose:
      - "3030"
    restart: unless-stopped

  rabbitmq:
    image: chat21/chat21-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      JWT_RABBIT_SECRET: ${CHAT21_JWT_SECRET}
      # NO definir RABBITMQ_DEFAULT_USER / PASS
    expose:
      - "5672"
      - "15672"
      - "1883"
      - "15675"
    restart: unless-stopped

  redis:
    image: redis:7.0.5
    expose:
      - "6379"
    restart: unless-stopped
